name: wompi_webview_example
description: "Example for wompi_webview"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cuid2: ^3.1.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  webview_flutter: ^4.11.0
  wompi_web_checkout:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
