name: wompi_web_checkout
description: "A Dart package that provides a seamless integration with Wompi's web checkout system, allowing you to easily implement payment processing in your Flutter applications."
version: 1.0.0+1
homepage: https://github.com/atleugim/wompi_web_checkout
repository: https://github.com/atleugim/wompi_web_checkout.git

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  crypto: ^3.0.6

dev_dependencies:
  very_good_analysis: ^7.0.0
