name: wompi_web_checkout
description: "A Dart package for Wompi's web checkout."
version: 1.0.0
homepage: https://github.com/atleugim/wompi_web_checkout
repository: https://github.com/atleugim/wompi_web_checkout.git

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  crypto: ^3.0.6

dev_dependencies:
  very_good_analysis: ^7.0.0
